import { Prompt } from "next/font/google";
import "./globals.css";

const promptFont = Prompt({
  variable: "--font-prompt",
  subsets: ["thai", "latin"],
  weight: ["300", "400", "500", "600", "700"], // คุณสามารถเลือกเฉพาะน้ำหนักที่ต้องการได้
});

export const metadata = {
  title: "PathCorTax",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="th">
      <body className={`${promptFont.variable} antialiased`}>{children}</body>
    </html>
  );
}
