services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: career-ai-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APP_PATH=/app
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_DEBUG=True
      - EMBEDDING_MODEL=intfloat/e5-small-v2
      - LLM_MODEL=llama3.1:latest
      - LLM_API_BASE=http://host.docker.internal:11434
      - FINE_TUNED_MODEL=llama3.1-8b-instruct-fine-tuned
      - USE_FINE_TUNED=True
    volumes:
      - ./data:/app/data
    entrypoint: ["/app/entrypoint.sh"]
    command:
      ["uvicorn", "src.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - llm-service

  llm-service:
    image: ollama/ollama:latest
    container_name: career-ai-llm
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    command: serve

volumes:
  ollama-data:
