services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      # - OLLAMA_HOST=http://ollama:11434
      - VECTOR_DB_PATH=/app/data/vector_db/job_knowledge

  # Frontend Web App
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #     - /app/.next
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://backend:8000
  #     - NEXTAUTH_URL=http://localhost:3000
  #     - NEXTAUTH_SECRET=your_nextauth_secret
  #     - GOOGLE_CLIENT_ID=your_google_client_id
  #     - GOOGLE_CLIENT_SECRET=your_google_client_secret
  #   depends_on:
  #     - backend
