FROM python:3.9-slim

WORKDIR /app

# ตั้งค่า environment variable สำหรับ Docker
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV APP_PATH=/app

RUN pip install --upgrade pip

# ติดตั้ง dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install sentence-transformers
# คัดลอกโค้ดและข้อมูลทั้งหมด
COPY . .

RUN echo ls

# สร้างโฟลเดอร์ที่จำเป็น
RUN mkdir -p /app/data/embedding /app/data/processed /app/data/raw /app/data/vector_db \
    /app/data/fine_tune /app/logs /app/uploads /app/data/users

RUN python src/data_collection/jobsdb_scraper.py

# เปิดพอร์ตสำหรับ API
EXPOSE 8000

# รันแอปพลิเคชัน
CMD ["uvicorn", "src.api.app:app", "--host", "0.0.0.0", "--port", "8000"]